### ISSUE TITLE
Tools re-verification and re-validation

### ISSUE THREAD

**Issue by henry-lp** [eclipse/repairnator#1002]
Aside from NPEFix, all of the following tools below either failed to generate patches as intended or PR fails due to patch corruption. Down here is the cmds to reproduce the case after fresh cloning master of repairnator and compile pipeline for jar and the result I got . The build ids are all taken from Junit test cases.  This is important to further develop the plugin :) . 

* AssertFixer: java -jar target/repairnator-pipeline-3.2-SNAPSHOT-jar-with-dependencies.jar -b 365127838 --createPR --ghOauth [your-git-token] --repairTools AssertFixer
  * found patches - work, but are corrupted , so PR failed.

* AstorJKali: java -jar target/repairnator-pipeline-3.2-SNAPSHOT-jar-with-dependencies.jar -b 376820338 --createPR --ghOauth [your-git-token] --repairTools AstorJKali
  * test failure

* AstorJMut: java -jar target/repairnator-pipeline-3.2-SNAPSHOT-jar-with-dependencies.jar -b 376847154 --createPR --ghOauth [your-git-token] --repairTools AstorJMut
  * java.lang.OutOfMemoryError: GC overhead limit exceeded (still work maybe ?)

* NopolTestExclusionStrategy: java -jar target/repairnator-pipeline-3.2-SNAPSHOT-jar-with-dependencies.jar -b 207890790 --createPR --ghOauth [your-git-token] --repairTools NopolTestExclusionStrategy
  * PATCH_NOT_FOUND

* SequencerRepair:
  does not work at all - IndexOutOfBoundsException, also the ServiceLoader failed to load the tools and therefore I had to load it manually, but it still failed after that - maybe someone know the correct cmd to run it ? 

* NPEFixSafe:java -jar target/repairnator-pipeline-3.2-SNAPSHOT-jar-with-dependencies.jar -b 252712792 --createPR --ghOauth [your-git-token] --repairTools NPEFixSafe
  * test failure

**Comment by monperrus** [comment]
Hi Henry,

Thanks for the analysis. We'll have a case-by-case strategy.

For AstorJKali, @dginelli is working on this right now, I suggest you meet to understand and fix the problem.

Thanks!

**Comment by dginelli** [comment]
Based on some experiments that I did, I think that the problem with AstorJKali could be related to the fault localization used by Repairnator.

Indeed, running Repairnator with GZoltar (I commented [these two lines](https://github.com/eclipse/repairnator/blob/5db00df5a40b0ee56877e93784aa0012061f4d29/repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java#L91-L92)), AstorJKali found a patch.

On the contrary, running Repairnator with CoCoSpoon, Repairnator didn't find any patch.

So, based on these aspects, I ran directly Astor on the same build in order to compare the suspicious statements found by GZoltar and by CoCoSpoon.

GZoltar found these six suspicious statements:

1. Candidate [className=mooctest.IntMax, methodName=max(III)I, lineNumber=9, susp=1.0]
2. **Candidate [className=mooctest.IntMax, methodName=max(III)I, lineNumber=10, susp=1.0]**
3. Candidate [className=mooctest.IntMax, methodName=max(III)I, lineNumber=4, susp=0.7905694150420948]
4. Candidate [className=mooctest.IntMax, methodName=max(III)I, lineNumber=5, susp=0.7905694150420948]
5. Candidate [className=mooctest.IntMax, methodName=max(III)I, lineNumber=7, susp=0.7905694150420948]
6. Candidate [className=mooctest.IntMax, methodName=max(III)I, lineNumber=6, susp=0.4472135954999579]

CoCoSpoon found these five suspicious statements:

1. Candidate [className=mooctest.IntMax, methodName=null, lineNumber=9, susp=1.0]
2. Candidate [className=mooctest.IntMax, methodName=null, lineNumber=7, susp=0.7905694150420948]
3. Candidate [className=mooctest.IntMax, methodName=null, lineNumber=5, susp=0.7905694150420948]
4. Candidate [className=mooctest.IntMax, methodName=null, lineNumber=4, susp=0.7905694150420948]
5. Candidate [className=mooctest.IntMax, methodName=null, lineNumber=6, susp=0.4472135954999579]

As you can see, unlike GZoltar, CoCoSpoon didn't find the suspicious statement in `line 10` of class `mooctest.IntMax`. To generate a patch, the repair tool has to remove exactly that statement. Since CoCoSpoon doesn't consider this statement as suspicious, Repairnator when uses CoCoSpoon with AstorJKali doesn't manage to generate a patch.

**Comment by henry-lp** [comment]
I don't know much in depth about the pros and cons about GZoltar and Cocospoon. Do you suggest that we switch to GZoltar ? :)

**Comment by dginelli** [comment]
About one month ago, we decided to use CoCoSpoon instead of GZoltar, because Repairnator has some problems using GZoltar (e.g., in many cases it doesn't find any suspicious locations and so it is impossible to try to generate a fix). 

In this particular case (build 376820338) it seems that GZoltar works better than CoCoSpoon because it finds the correct suspicious location, but in this moment I don't know why CoCoSpoon is not able to do the same. It would be interesting to understand the reason.

Looking at the test cases of repairnator-pipeline, I saw that the test case that uses the build 376820338 is [this one](https://github.com/eclipse/repairnator/blob/b7895a481e54a1036d2a13cac99523be25200fc0/repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestAstorRepair.java#L59), but I think it is not usually executed because of `@Ignore` at the beginning of the class.

If you need some builds for which Repairnator is able to generate a patch using AstorJKali and CoCoSpoon, you can try using these ones: 368867994 and 380634197. In theory, it should be working.

**Comment by henry-lp** [comment]
Yes , I also remember some PR related to this change some months ago . Thanks a lot for the ids, I'll try that out later. If everything works well , we can consider the issue with AstorJKali tool fixed.
