### ISSUE TITLE
scanning from Github commits (incl. Github actions)

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#1147]
Since the Travis scanners are not good anymore, an alternative would be to scan from Github instead.

* Get the last commits
  * through the Github API
  * or through the Github Torrent API (or another alternative)
* Get the commit status through the Github API
* If there is a status from Travis-ci.com or Travis-ci.org, go and get the build/job info through the Travis API

**Comment by khaes-kth** [comment]
@monperrus @javierron @cokefh 
I was looking for the Github Actions api and I did not find how we can collect all the failed actions through that path.

So, I decided to do this:
1- periodically, look for recently updated projects with a pom.xml file at their root.
2- collect their recent commits.
3- filter the commits that have a Github Actions or Travis CI not-successful build.
4- report these commits.

I implemented a very simple and not clean version of this algorithm. It is available here: [https://github.com/khaes-kth/failed-build-collector](https://github.com/khaes-kth/failed-build-collector)

You can access the service provided by this code here: [http://130.237.222.185:8080/failed-commits/2020-11-20-15](http://130.237.222.185:8080/failed-commits/2020-11-20-15)

You can replace "2020-11-20-15" with "year-month-day-hour" and it gives you the corresponding failed commits in that hour. The data is collected (and hopefully, will be collected) since 2020-11-20-13. At any moment, the last checked hour would be 5 hours ago because we need to give some time to see if a build fails or not.

**Comment by javierron** [comment]
Thanks @khaes-kth, this is great!

IMO, the next step would be to integrate this scanner in (or read from Khashayar's service from) Repairnator, and tweak the  pipeline laucher to use this data and trigger the builds.

I believe in general, this could be a much better way to scan and trigger builds. It seems more efficient and extensible than the current travis-ci-only approach.

In fact, if we scan commits like this, what is limiting us now from using only GitHub Actions and Travis-CI? Couldn't we just get them all? WDYT?

**Comment by khaes-kth** [comment]
> if we scan commits like this, what is limiting us now to use only GitHub Actions and Travis-CI? Couldn't we just get them all?

Yes, we can (probably) easily extend this version and get also other types of build failures. But we should somehow define "failed build", unless we have so much computation power that we can rebuild all commits locally, regardless of their status.



> this could be a much better way to scan and trigger builds

Since I am not familiar with Repairnator code, I am not sure about this. But as far as I remember, you said that having the repo-name and commit-id, would conceptually be enough to trigger the pipeline, so I thought this service would be useful.

I also think that we can embed this service into Repairnator: whenever we start Repairnator, we also start "failed-build-collector service" as a part of it; then, Repairnator's scanner only scans this one service instead of scanning "travis.com", "travis.org", "github-actions.com", ...

I also wanted to note one point: this version of the service only monitors repos with at least 1 star (because there are many 0 star projects, that would take too long to monitor).

**Comment by monperrus** [comment]
That's great!

> 1- periodically, look for recently updated projects with a pom.xml file at their root.

How often?

> 2- collect their recent commits.

How often?

> IMO, the next step would be to integrate this scanner in (or read from this service from) Repairnator, and tweak the pipeline laucher to use this data and trigger the repair attempts.

Yes, tweaking the pipeline is good. Instead of 

    ./pipeline --build 123456

we need something like

    ./pipeline --slug orga/reponame --commit abcedf42abcdef

@dginelli has something close to this!

**Comment by khaes-kth** [comment]
> How often?

Once in an hour it checks the commits until 6 hours ago. For example, it is Nov 23, 11:40 right now and we have the results for Nov 23 05:00 here: [http://130.237.222.185:8080/failed-commits/2020-11-23-05](http://130.237.222.185:8080/failed-commits/2020-11-23-05)

**Comment by dginelli** [comment]
> we need something like
> 
> ```
> ./pipeline --slug orga/reponame --commit abcedf42abcdef
> ```
> 
> @dginelli has something close to this!

Yes, it's the `GitRepositoryLauncher` mode. You can read the documentation in [this page](https://github.com/eclipse/repairnator/blob/master/doc/main-classes.md#pipeline-frinriaspiralsrepairnatorpipelinegitrepositorylauncher).

The Java class that manages this type of execution is [GitRepositoryLauncher](https://github.com/eclipse/repairnator/blob/master/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/GitRepositoryLauncher.java).

**Comment by monperrus** [comment]
Thanks Davide for the pointer.

> Once in an hour it checks the commits until 6 hours ago. 

That may be too slow for making live PRs. Could we do every 20 minutes?

**Comment by monperrus** [comment]
FYI
Moving away from Travis CI
https://ropensci.org/technotes/2020/11/19/moving-away-travis/

**Comment by monperrus** [comment]
See #1162

**Comment by monperrus** [comment]
closed per #1168
