### ISSUE TITLE
add support for daily summary email

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#734]
- current date
- number of analyzed builds
- number of repair attempts
- total number of patches
- number of patches per tool

**Comment by btellstrom** [comment]
We wish to notify a list of users at certain time intervals. Currently, our notification is based upon whether we find a patch or not, and these notifications are handled by the pipeline. A summary email seems more fitting to be run from the RTScanner itself, especially considering that the email should be about the RTScanners current performance and behaviour.

To implement this, a new notifierEngine should be used and run from the RTScanner. However, there are effectively three possible classes where it could be included. 
1. In the RTScanner itself. Let the notifierEngine also implement runnable, and upon launch of the scanner start it as a separate thread alongside InspectJobs and InspectBuilds and have it wake up at certain times to check its send criteria. One could let the thread sleep for a long time and thus not have it consume that much resources.
2. In InspectJobs. InspectJobs is constantly running and to have it check whether the criteria for sending a summary email as one step in its loop would ensure it checks often (which is not necessary), prevent the creation of another thread. 
3. In InspectBuilds. InspectBuilds run much less often than InspectJobs so the checks would be less frequent, but if we are very unlucky we might not find any interesting builds in a while, resulting in potentially a large variance of when the emails are sent (this issue will most likely become much smaller as time goes on).

My personal proposal would be 1, allowing us more control and it being more elegant for the actual RTScanner to send the email rather than the inspectors.

**Comment by monperrus** [comment]
Thanks a lot for the clear summary. Solution 1 looks good to me as well.

**Comment by bloriot97** [comment]
I think the first solution is the best as well, it makes the summary independent from the realtime scanner, except for the 'triggering'.

**Comment by surli** [comment]
> A summary email seems more fitting to be run from the RTScanner itself

I'm not sure about this assumption since you want to send data that are coming directly from the pipeline itself, such as the number of patches by tool, etc. 

Basically, what's needed here is to be able to aggregate some data coming from different component of Repairnator (namely the scanner and the pipeline). 

So for a first implem, you can indeed create a dedicated thread in RTScanner, retrieve the data from the database and send a summary email, but it does not look that elegant since it creates a dependency between the pipeline and the scanner that we don't necessarily want. 

On the long term view, I'd see more a dedicated component for Repairnator to consume the data produced by its different parts. Then this component would have the responsiblity to process this data according to different strategies: send emails, put them in fails, aggregate them in reports, etc. 

WDYT?

**Comment by btellstrom** [comment]
I think that sounds like a very good idea for the long term! For now I'll however begin with the thread approach, but as we add features of these kinds I agree that we should create a dedicated component for it.

**Comment by monperrus** [comment]
we never receive digest emails reopening
