### ISSUE TITLE
Test failing after adding maven-repair to repository

### ISSUE THREAD

**Issue by btellstrom** [eclipse/repairnator#808]
```
Failed tests: 
  TestAbstractStep.testGetPomOnProjectWithSubModule:116 
Expected: is "/tmp/test_get_pom_project_with_submodule2531020899353941363/repairnator/repairnator/pom.xml"
     but: was "/tmp/test_get_pom_project_with_submodule2531020899353941363/repairnator/maven-repair/pom.xml"
```
This test most likely fails because we now effectively have two projects, each with submodules and it simply finds the first one, rather than continue looking.

I would claim that this is most likely not a problem and that a solution would be to simply `@Ignore` the test while maven-repair remains in the repo.

**Comment by monperrus** [comment]
per our discussion, `getPom` should throw an exception if there are several matching pom.xml in the repo. In addition, we could create a method `getPoms()` which returns a list of subpoms in fixed, alphabetical order.

**Comment by fermadeiral** [comment]
> per our discussion, getPom should throw an exception if there are several matching pom.xml in the repo.

@monperrus but I think that if this is done, repairnator will not consider multi-module projects anymore, since they have more than one pom.xml. My point is: the implementation to solve the issue can't be simply counting pom.xml files in the repo and throwing an exception if there is more than one. I think that is necessary to do an analysis on folder depth, starting from the root. If the root has one pom, this is the good one. Otherwise, the pom.xml should be searched in the first folder level, and then counting them, etc.

**Comment by surli** [comment]
Agreed with Fernanda. Actually for me the test was good but should have contained a specific commit ID to checkout.

So I'd say that now we should have to test:
  1. the same one with a  checkout of a commit before adding maven-repair
  2. a new one with a checkout of latest commit, with an assert on maven-repair/pom.xml: it's the first one in alphabetical order, so it's good.

My 2 cents.
