### ISSUE TITLE
feat: add new component BuildRainer

### ISSUE THREAD

**Issue by monperrus** [eclipse/repairnator#899]
BuildRainer listens to @tdurieux's web socket from https://travis-ci.com/tdurieux/travis-listener/ and pushes build ids to the ActiveMQ.

This would go in `repairnator/build-rainer` in Java.

**Comment by Tailp** [comment]
Hi :), here is the prototype [link](https://github.com/Tailp/travis-listener/tree/ActiveMQ-BuildRainer). It's in Nodejs . Instructions are in readme, section `Run as ActiveMQ BuildRainer for Repairnator` .  I modified  scripts/collect.js so that it redirect failed, java build ids to ActiveMQ server. Also, it check the size of queue using JMX each time to run in slow/sleep mode if the number of message exceed queue limit (set by enviroment var). This enable us to use the websocket directly without any middle component.
