### ISSUE TITLE
Stablize CI build

### ISSUE THREAD

**Issue by jianguda** [eclipse/repairnator#943]
To continue "issue844" branch, we need one stable CI build. Check [this comment](https://github.com/eclipse/repairnator/pull/932#issuecomment-528843023) of #932 for detailed info.

**Comment by monperrus** [comment]
I don't understand the problem with the organization name. What should we change?

**Comment by jianguda** [comment]
I am not mean the organization name, but I find CI environment changed meanwhile.

**Comment by jianguda** [comment]
This repo's CI migrated from `travis-ci.org` to `travis-ci.com`. I am not sure whether there exist some differences between them, or some issues got left during our migration, but I feel it is exactly this change that affected CI build.

**Comment by monperrus** [comment]
Agree, but I don't understand the root cause and I don't see what and where to change. Any idea?

**Comment by jianguda** [comment]
I have no idea, either.

I am trying to make all test files run as separate jobs, as one temporary solution.

**Comment by jianguda** [comment]
Hey @monperrus 

Maybe the root cause is the inaccessibility of old builds. It blocks our testing job and let CI build fail for _"The job exceeded the maximum time limit for jobs, and has been terminated"_.

For example, we are not able to visit [build380717778](https://travis-ci.org/Spirals-Team/repairnator/builds/380717778) any more. Some test cases need to access old builds.

Based on [documentation](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#what-information-will-not-be-transferred-to-travis-cicom):
_Previous build history - your builds from before the migration to travis-ci.com will remain on travis-ci.org until the complete build- history migration (sometime in early Q3 2019)_

So it should not be one big deal if we just migrate from `travis-ci.org` to `travis-ci.com`. It is the change of owner that made our situation weird.

**Comment by jianguda** [comment]
WDYT?

**Comment by monperrus** [comment]
Very nice analysis, thank!

Yes, link https://travis-ci.org/Spirals-Team/repairnator/builds/380717778 is dead but
https://travis-ci.org/eclipse/repairnator/builds/380717778 now exists.

At the API level, it's still OK: https://api.travis-ci.org/v3/build/380717778

Since we query the Travis API with only the build id, I still don't completely understand.

Test PR: https://github.com/eclipse/repairnator/pull/945

**Comment by jianguda** [comment]
It is found that CI env-variables are only set at `travis-ci.org`, ignoring `travis-ci.com`.

**Comment by monperrus** [comment]
We're getting closer to a CI fix. It seems that the update of Astor causes the build to fail. I suspect that a dependency change in Astor causes AssertFixer to crash. I'm on it.

**Comment by monperrus** [comment]
Fixed

**Comment by monperrus** [comment]
For the record, here is the explanation

When we updated Astor (https://github.com/eclipse/repairnator/commit/a51387928a6789279a8e98c8aa2118856e846b0c), the new version of Astor came with newer version of the dependencies. Since Astor was before assert-fixer in the pom.xml, this changed the runtime dependencies of assert-fixer. One such change was not backward compatible for assert-fixer. The fix was to switch the two dependencies https://github.com/eclipse/repairnator/commit/3b30054f18f4de797e45145af879d9d00350ecc9#diff-9ab40a54cf9289815466c35ec158c2d9L86
