### ISSUE TITLE
Building repairnator on macos

### ISSUE THREAD

**Issue by gustavopinto** [eclipse/repairnator#997]
When I'm trying to compile repairnator using ``mvn compile'' on macos (10.14.4), and I receive the following error: 

```
[ERROR] Failed to execute goal on project repairnator-pipeline: Could not resolve dependencies for project fr.inria.repairnator:repairnator-pipeline:jar:3.2-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.4.2 at specified path /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
```

However, it seems that the JDK tools in macos are slightly different than other unix platforms (see https://developer.apple.com/library/archive/documentation/Java/Conceptual/Java14Development/02-JavaDevTools/JavaDevTools.html). For instance, tools.jar does not exit. 

What should I do then? I thought of creating a symbolic link from classes.jar to tools.jar, but it sounds like a workaround.

**Comment by monperrus** [comment]
> I thought of creating a symbolic link from classes.jar to tools.jar, but it sounds like a workaround.

Yes, it is. It's been a long time that Java is not anymore a platform-independent runtime.

**Comment by jianguda** [comment]
Hey @gustavopinto 
I met this issue few months ago, then I turn to use maven downloaded from https://maven.apache.org and it works
Maybe you could try this (if I remembered this thing correctly)

**Comment by gustavopinto** [comment]
Hi @jianguda, 
thanks for your response. I downloaded maven and installed maven manually, but I kept receiving the same error mentioned. 

I then tried to create this symbolic link. After that, the VM crashed during the testing phase. 

``Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project repairnator-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?``

Any pointers here?

BTW, I'm using maven 3.6.3 and Java 13.0.1.

**Comment by jianguda** [comment]
Hey @gustavopinto 
I tried to reproduce this issue but get stuck in other strange issues.

Hey @henry-lp , have you met this issue, or do you know how to solve? Thanks!

**Comment by henry-lp** [comment]
Hey @jianguda and @gustavopinto :) ,
Just cloned a fresh copy of repairnator and compiled in the repairnator-pipeline folder and it works fine on my machine (Ubuntu) 

As @gustavopinto linked, this is a quite known plattform issue in MacOs. Since our repairnator relies on tools.jar to run, we can't ensure the usual behaviors of repairnator. The symbolic link solution will not work because I think repairnator will still assume during runtime that there is a tools.jar at the original location without paying attention to the symbolic link. What I think you can do is to include this dependency in the pom mentioned in this [post](https://stackoverflow.com/questions/8375423/missing-artifact-com-suntoolsjar)
```
<dependency>
   <groupId>com.sun</groupId>
   <artifactId>tools</artifactId>
   <version>1.6</version>
   <scope>system</scope>
   <systemPath>/Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/../lib/tools.jar</systemPath>
 </dependency>
```
Unfortunately I don't have time to set up a macos VM to debug this since I am busy with other tasks. If you only want to run repairnator for repair consider dowloading the latest jar-with-dependencies [here](https://oss.sonatype.org/content/repositories/snapshots/fr/) and hopefully it will run without issue :) .
 
--Cheers

**Comment by gustavopinto** [comment]
Hi @henry-lp, thanks for your response.

As far as I could tell, I could only hardcode the tools.jar location if I indeed have it (which in case of macos, I don't have). Also, I think that maven is indeed finding tools.jar (the symbolic link one), otherwise the JVM would not crash after using the symbolic link. 

Anyway, I included this dependency, but the error changed to the following one: 

```
[ERROR] Failed to execute goal on project repairnator-root: Could not resolve dependencies for project fr.inria.repairnator:repairnator-root:pom:3.2-SNAPSHOT: Could not find artifact com.sun:tools:jar:1.6 at specified path /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home/lib/tools.jar -> [Help 1]
```

Funny enough, this is the correct path, but it may be a problem with the symbolic link. 

I have another PC with linux installed. I will let you know if I have any problems compiling repairnator there (but only next year).

In any case, I don't want to use repairnator just for repair. In fact, I do want to onboard on the team. I will visit @monperrus next year to work on repairnator and I would like to get acquainted with it before my arrival. :-)

Gustavo

**Comment by henry-lp** [comment]
Hi @gustavopinto,
I understand and sure, it's a pleasure to be of help :) . I guess in this case , you'll have no other choice than fixing it in your current OS or maybe it's better to just move to Linux to avoid different plattform as final option. 
--Cheers

**Comment by surli** [comment]
The problem is actually that you have JDK 13 installed: tools.jar has been removed from JDK since Java 9, see http://openjdk.java.net/jeps/220 for details.

So for now I suggest you to install JDK 8 on your machine to run Repairnator (using homebrew for example), but the fact is that this dependency should be removed ASAP.

**Comment by gustavopinto** [comment]
Hello @surli. Thanks for your reply.

Yes, downgrading to JDK 8 worked fine, thanks!

I will leave this issue open in case you want to fix this issue in the future.

**Comment by monperrus** [comment]
issue to be closed?

**Comment by monperrus** [comment]
Thanks Gustavo!
